In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [31]:
df = pd.read_csv("C:/Users/gpro0/OneDrive/Рабочий стол/train.csv")
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [33]:
df.isna().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [35]:
for i in df.select_dtypes(['object']).columns:
    df[i] = df[i].fillna(df[i].mode()[0])
df.isna().sum()

PassengerId       0
HomePlanet        0
CryoSleep         0
Cabin             0
Destination       0
Age             179
VIP               0
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name              0
Transported       0
dtype: int64

In [37]:
for i in df.select_dtypes(include=['float']).columns:
    df[i]=df[i].fillna(df[i].mean())
df.isna().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

In [38]:
df.drop(["PassengerId", "Cabin", "Name"], axis=1, inplace = True)
df.head

<bound method NDFrame.head of      HomePlanet  CryoSleep    Destination   Age    VIP  RoomService  \
0        Europa      False    TRAPPIST-1e  39.0  False          0.0
1         Earth      False    TRAPPIST-1e  24.0  False        109.0
2        Europa      False    TRAPPIST-1e  58.0   True         43.0
3        Europa      False    TRAPPIST-1e  33.0  False          0.0
4         Earth      False    TRAPPIST-1e  16.0  False        303.0
...         ...        ...            ...   ...    ...          ...
8688     Europa      False    55 Cancri e  41.0   True          0.0
8689      Earth       True  PSO J318.5-22  18.0  False          0.0
8690      Earth      False    TRAPPIST-1e  26.0  False          0.0
8691     Europa      False    55 Cancri e  32.0  False          0.0
8692     Europa      False    TRAPPIST-1e  44.0  False        126.0

      FoodCourt  ShoppingMall     Spa  VRDeck  Transported
0           0.0           0.0     0.0     0.0        False
1           9.0          25.0   549.0    44.0         True
2        3576.0           0.0  6715.0    49.0        False
3        1283.0         371.0  3329.0   193.0        False
4          70.0         151.0   565.0     2.0         True
...         ...           ...     ...     ...          ...
8688     6819.0           0.0  1643.0    74.0        False
8689        0.0           0.0     0.0     0.0        False
8690        0.0        1872.0     1.0     0.0         True
8691     1049.0           0.0   353.0  3235.0        False
8692     4688.0           0.0     0.0    12.0         True

[8693 rows x 11 columns]>

In [40]:
col = df.select_dtypes(['object']).columns
le=LabelEncoder()
for i in col:
    df[i]=le.fit_transform(df[i])
df.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,1,False,2,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,0,False,2,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,1,False,2,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,1,False,2,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,0,False,2,16.0,False,303.0,70.0,151.0,565.0,2.0,True

In [41]:
x = df.drop("Transported", axis=1)
y = df.Transported

In [42]:
trainx, testx, trainy, testy = train_test_split(x, y, test_size = 0.3)

In [43]:
dt = DecisionTreeClassifier()
model_dt = dt.fit(trainx, trainy)
pred_dt = model_dt.predict(testx)
print(confusion_matrix(testy, pred_dt))
print(accuracy_score(testy, pred_dt))

[[923 384]
 [325 976]]
0.7281441717791411

In [44]:
knn = KNeighborsClassifier()
model_knn = knn.fit(trainx, trainy)
pred_knn = model_knn.predict(testx)
print(confusion_matrix(testy, pred_knn))
print(accuracy_score(testy, pred_knn))

[[1005  302]
 [ 276 1025]]
0.7783742331288344

In [45]:
nb = GaussianNB()
model_nb = nb.fit(trainx, trainy)
pred_nb = model_nb.predict(testx)
print(confusion_matrix(testy, pred_nb))
print(accuracy_score(testy, pred_nb))

[[ 612  695]
 [ 106 1195]]
0.6928680981595092

In [46]:
lr = LogisticRegression()
model_lr = lr.fit(trainx, trainy)
pred_lr = model_lr.predict(testx)
print(confusion_matrix(testy, pred_lr))
print(accuracy_score(testy, pred_lr))

[[ 992  315]
 [ 251 1050]]
0.7829754601226994

c:\Users\gpro0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(